name: Frontend QA Deploy

on:
  pull_request:
    types: [closed]
    branches: ["develop"]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: ./yobuddy
        run: npm ci

      - name: Create .env.qa
        working-directory: ./yobuddy
        run: |
          echo "VUE_APP_API_BASE=${{ secrets.QA_API_URL }}" > .env.qa

      - name: Build Frontend (QA)
        working-directory: ./yobuddy
        run: npm run build:qa

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./yobuddy
          push: true
          tags: iiijong/yobuddy-frontend:qa

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - run: docker pull iiijong/yobuddy-frontend:qa

      - working-directory: C:\Users\Playdata\Desktop
        run: |
          docker compose down
          docker compose up -d
